print("KS Area of Square Calculator")
print("")
print("Made by:- Kunal Singh")
print("Class Xth-C")
print("Kendriya Vidyalaya No.1, AFS Hindan")
print("Session:- 2022-2023")
print("")
print("Area of Square = Side x Side")
side = float(input("Side of Square = "))
print("Area of Square = " ,side ,"x" ,side)
area = side*side
print("Area of this square is ", area)
print("")
input("Any Feedback - ")
print("The AI has recorded your experience & feedback, we have sent your experience and feedback (if any) to the developer.")
print("Thankyou for using KS Area of Square Calcuator to find area of the square.")
print("Have a nice day!")
print("")
print("Contact Developer:- singhk122007@gmail.com")
